### ISSUE TITLE
Cristina student todo's

### ISSUE THREAD

**Issue by akotlar** [akotlar/bystro#48]
A mixture of web and local tasks:

- [ ] Create new save filters, Go or Perl.

- [ ] Create in-line documentation on web: documentation should appear for new users (or users who haven't seen the function previously), when they are on a page/section with that function. Can be pretty easily written in Angular Material.

- [ ] Document new fields going up in master (web)

- [ ] Document new UNIT SEPARATOR (ASCII 31) for overlapping fields

- [ ] Document filters

- [ ] Contribute to VCF / plink export

- [ ] Contribute to Hail integration
